"""Added foreign key for tournament.games relationship

Revision ID: 964721fe74e8
Revises: 50c6bf5743cc
Create Date: 2020-02-22 22:12:07.850484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964721fe74e8'
down_revision = '50c6bf5743cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('tournament', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'tournament', ['tournament'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'tournament')
    # ### end Alembic commands ###
